[package]
name = "tg-rcore-tutorial-easy-fs-zgy"
description = "A simple filesystem implementation for rCore tutorial OS."
version = "0.4.8"
edition = "2024"
authors = ["Guangye Zhao <zhaogy23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/Nullsire/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-easy-fs"
homepage = "https://github.com/rcore-os/tg-rcore-tutorial-easy-fs/tree/test"
documentation = "https://docs.rs/tg-rcore-tutorial-easy-fs"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded", "os"]

[dependencies]
spin = "0.9"
bitflags = "1.2"
