[package]
name = "tg-rcore-tutorial-ch1-extended"
description = "Chapter 1 of rCore Tutorial (Extended): Bare-metal env building alongside VirtIO GPU framebuffer interaction in RISC-V S-mode."
version = "0.0.1"
edition = "2024"
authors = ["Guangye Zhao <zhaogy23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/Nullsire/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-ch1"
documentation = "https://docs.rs/tg-rcore-tutorial-ch1"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded", "os"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-sbi = { package = "tg-rcore-tutorial-sbi", path = "../tg-rcore-tutorial-sbi", version = "0.4.8", features = ["nobios"] }
# 在裸机上引入通用 VirtIO 硬件规范通信协议栈，借由抽象以驱动 MMIO 分配的 QEMU 外围设备。
virtio-drivers = "0.7.2"
# 在独立环境实现对未分配内存池的基础动态管控（通常需借助算法保证效率与防碎片），为实现队列以及硬件通信载体所需的堆空间需求提供支援。
buddy_system_allocator = "0.9"